language: ruby
rvm:
  - 2.7.2
services:
  - postgresql
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 12
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec